---
driver:
  name: digitalocean

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12-04-x64

suites:
  - name: database_user
    run_list:
      - recipe[widget_world_application::database_user]
    attributes:
  - name: default
    run_list:
      - recipe[widget_world_application::default]
    attributes:
