name             'widget_world_application'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures widget_world_application'
long_description 'Installs/Configures widget_world_application'
version          '0.1.0'
depends          'widget_world_postgres'
depends          'widget_world_ruby'
depends          'widget_world_apache'
depends          'widget_world_passenger'
