name             'widget_world_passenger'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures widget_world_passenger'
long_description 'Installs/Configures widget_world_passenger'
version          '0.1.0'
depends          'apt'
